name: Kevin Clark
markdown: kramdown
pygments: true
permalink: /articles/:title/
exclude: ['node_modules', 'Gruntfile.js', 'package.json']
__default_layouts:
  default: default      # everything that doesn't have another default specified
  _posts: article-indv
dribbble_set:
  user: 'vernalkick'
  shots_per_page: 24
  page: 1
kramdown:
  input: GFM