name: Kevin Clark
markdown: redcarpet
pygments: true
permalink: /articles/:title/
excerpt_separator: ""
jekyll_models: [library]
portfolio_categories: ["Web", "Identity"]
site_base: /
navigation:
- text: Home
  url: /
- text: Articles
  url: /articles/
- text: Portfolio
  url: /portfolio/
- text: About
  url: /about/
__default_layouts:
  default: default      # everything that doesn't have another default specified
  _posts: post-indv     # all posts
  portfolio: portfolio-indv    # everything in magic/