name: Kevin Clark
url: http://kevinclark.ca
description: "Pixels, shapes and words"
author: Kevin Clark
rss_path: /rss
rss_name: index.xml
markdown: kramdown
permalink: /articles/:title/
sass:
  sass_dir: assets/stylesheets
exclude: ['node_modules', 'Gruntfile.js', 'package.json']
__default_layouts:
  default: default      # everything that doesn't have another default specified
  _posts: article-indv
dribbble_set:
  user: 'vernalkick'
  shots_per_page: 24
  page: 1
kramdown:
  input: GFM
  use_coderay: true
  coderay:
      coderay_line_numbers:      nil
      coderay_tab_width:         2
      coderay_bold_every:        false
      coderay_css:               class
