name: Kevin Clark
markdown: redcarpet
pygments: true
permalink: /articles/:title/
jekyll_models: [library]
site_base: /
navigation:
- text: Home
  url: /
- text: Articles
  url: /articles/
- text: Portfolio
  url: /portfolio/
- text: About
  url: /about/